### ISSUE TITLE
Missing class

### ISSUE THREAD

**Issue by christophlehmann** [MaxServ/t3ext-parsedown#1]
When I add the content element i get

Warning: Uncaught exception 'TYPO3\CMS\Core\Error\Exception' with message 'PHP Warning: require_once(typo3conf/ext/parsedown/Classes/Vendor/Erusev/Parsedown/Parsedown.php): failed to open stream: No such file or directory in typo3conf/ext/parsedown/Classes/UserFunctions/Tca.php line 29

via TER and git clone (without composer)

**Comment by Tuurlijk** [comment]
Should be fixed since 1.0.3
